#java makefile
makefile:
clean: rm bin
build: bin start java build python, python3.5 conflict.py
rebuild: clean, bin start java build python, python3.5 conflict.py
make: java bin start python end
remake: rm pythonend.pcs, java bin start python end
buildjava: javac conflict.py java conflict.py
buildpython: python3.5 conflict.py
