 language: python
 env:
   - R_LIBS_USER=~/R
 install:
   - sudo apt-add-repository -y ppa:marutter/rdev
   - sudo apt-get install git
 before-install:
   - sudo apt-get update
   - sudo apt-get install git-extras
 before-script:
   - git status
 script: 
   - echo "master project"
